#!/bin/sh
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
user=$(whoami)
hostname=$(hostname)
kernel=$(uname -r)
uptime=$(uptime -p)
#pkgs=$(dnf list --installed | wc -l)
name=$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^ *//')
cores=$(nproc)
freq=$(awk 'BEGIN{max=0} {if ($1>max) max=$1} END{printf "%.2f", max/1000000}' /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq)
mem=$(free -h | awk '/Mem:/ {print $3 " / " $2}')
disk=$(df -hT / | awk 'NR==2 {printf "%s / %s (%s) - %s\n", $4, $3, $6, $2}')
distro=$(. /etc/os-release && echo $ID)
logo=$(sed -n "/^===$distro===\$/,/^===END===\$/p" "$SCRIPT_DIR/distro_logos.txt" | sed '1d;$d')
printf '%b\n' "$logo"
#echo "$logo"
printf "╭───────────╮\n"
printf '%b' "│ \e[1;32m  user\e[0m   │" " $user\n"
printf '%b' "│ \e[1;31m󰍹  hname\e[0m  │" " $hostname\n"
. /etc/os-release && printf '%b' "│ \e[1;36m  distro\e[0m │" " $NAME\n"
printf '%b' "│ \e[1;35m  kernel\e[0m │" " $kernel\n"
printf '%b' "│ \e[1;33m  uptime\e[0m │" " $uptime\n"
printf '%b' "│ \e[1;32m  shell\e[0m  │" " $SHELL\n"
#echo "|   pkgs:  |" $pkgs #it takes too long, and it is specific for each distro, not worth it.
printf '%b' "│ \e[1;34m  cpu\e[0m    │" " $name ($cores) @ ${freq} GHz\n"
printf '%b' "│ \e[1;31m  memory\e[0m │" " $mem\n"
printf '%b' "│ \e[1;33m󰉉  disk\e[0m   │" " $disk\n"
printf "╰───────────╯\n"
